providers:

  openai:
    enabled: true
    models:
      - id: "gpt-5-nano"
        max_tokens: 6000

  gpt4all:
    enabled: true
    models:
      - id: "Meta-Llama-3-8B-Instruct.Q4_0.gguf"
        path: "./llm_models"
        device: "cpu"

embedding:
  model_name: "all-MiniLM-L6-v2"

runtime:
  max_input_chars: 3000
